name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      # - name: Run Tests
      #   working-directory: ./frontend
      #   run: npm test

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Firebase
        run: |
          cd frontend
          npx firebase-tools deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
